server:
  port: 8888 #更改tomcat端口

spring:
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/majhong?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  thymeleaf:
    #开启MVC thymeleaf 视图解析
    enabled: true
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
